// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.2
//   protoc               v3.20.3
// source: proto/projects.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "projects";

export enum ProjectType {
  WEB_SERVICE = "WEB_SERVICE",
  STATIC_SITE = "STATIC_SITE",
  IMAGE = "IMAGE",
}

export enum ProjectStatus {
  QUEUED = "QUEUED",
  BUILDING = "BUILDING",
  DEPLOYING = "DEPLOYING",
  DEPLOYED = "DEPLOYED",
  FAILED = "FAILED",
  STOPPED = "STOPPED",
}

export enum InstanceType {
  TIER_0 = "TIER_0",
  TIER_1 = "TIER_1",
  TIER_2 = "TIER_2",
}

export interface Project {
  id: string;
  name: string;
  status: ProjectStatus;
  createdAt: string;
  updatedAt: string;
  deploymentUrl?: string | undefined;
  projectType: ProjectType;
  instanceType: InstanceType;
}

export interface CreateProjectDto {
  name: string;
  projectType: ProjectType;
  instanceType: InstanceType;
  userId: string;
  imageData?: ImageData | undefined;
  webServiceData?: WebServiceData | undefined;
  staticSiteData?: StaticSiteData | undefined;
  env: Env[];
}

export interface GetUserDto {
  userId: string;
}

export interface RollbackProjectDto {
  projectId: string;
  deploymentId: string;
}

export interface GetProjectDto {
  projectId: string;
}

export interface PopulatedProject {
  id: string;
  name: string;
  status: string;
  createdAt: string;
  updatedAt: string;
  deploymentUrl?: string | undefined;
  projectType: ProjectType;
  deployments: Deployment[];
}

export interface Projects {
  projects: Project[];
}

export interface UpdateInstanceTypeDto {
  id: string;
  instanceType: InstanceType;
}

export interface UpdateDeploymentDto {
  id: string;
  updates: Updates | undefined;
}

export interface Updates {
  repoName?: string | undefined;
  userId: string;
  imageData?: ImageData | undefined;
  webServiceData?: WebServiceData | undefined;
  staticSiteData?: StaticSiteData | undefined;
  envs: Env[];
}

/** Deployment messages */
export interface Deployment {
  id: string;
  createdAt: string;
  updatedAt: string;
  status: string;
  imageData?: ImageData | undefined;
  webServiceData?: WebServiceData | undefined;
  staticSiteData?: StaticSiteData | undefined;
}

export interface Deployments {
  deployments: Deployment[];
}

export interface DeploymentLogs {
  deploymentBuildLog?: string | undefined;
  deploymentRunLog?: string | undefined;
}

export interface GetDeploymentDto {
  deploymentId: string;
}

export interface GetDeploymentsDto {
  projectId: string;
}

export interface CreateDeploymentDto {
  projectId: string;
  userId: string;
  env: Env[];
  imageData?: ImageData | undefined;
  webServiceData?: WebServiceData | undefined;
  staticSiteData?: StaticSiteData | undefined;
}

export interface ImageData {
  imageUrl: string;
  accessToken?: string | undefined;
  port: number;
}

export interface WebServiceData {
  repoUrl: string;
  runCommand: string;
  buildCommand: string;
  accessToken?: string | undefined;
  branch?: string | undefined;
  commitId?: string | undefined;
  port: number;
}

export interface StaticSiteData {
  repoUrl: string;
  outDir: string;
  buildCommand: string;
  accessToken?: string | undefined;
  branch?: string | undefined;
  commitId?: string | undefined;
}

export interface Request {
  deploymentId: string;
  ip: string;
  method: string;
  url: string;
  userAgent: string;
  referer: string;
  timestamp: string;
}

export interface Requests {
  requests: Request[];
}

/** Env messages */
export interface Env {
  name: string;
  value: string;
}

export interface Envs {
  envs: Env[];
}

export const PROJECTS_PACKAGE_NAME = "projects";

export interface ProjectsServiceClient {
  getAllProjects(request: GetUserDto): Observable<Projects>;

  getProject(request: GetProjectDto): Observable<PopulatedProject>;

  createProject(request: CreateProjectDto): Observable<PopulatedProject>;

  deleteProject(request: GetProjectDto): Observable<Project>;

  stopProject(request: GetProjectDto): Observable<Project>;

  startProject(request: GetDeploymentDto): Observable<Project>;

  updateInstanceType(request: UpdateInstanceTypeDto): Observable<Project>;

  rollbackProject(request: GetDeploymentDto): Observable<Deployment>;

  redeployProject(request: CreateDeploymentDto): Observable<Deployment>;

  retryAndDeployProject(request: GetDeploymentDto): Observable<Deployment>;
}

export interface ProjectsServiceController {
  getAllProjects(request: GetUserDto): Promise<Projects> | Observable<Projects> | Projects;

  getProject(request: GetProjectDto): Promise<PopulatedProject> | Observable<PopulatedProject> | PopulatedProject;

  createProject(request: CreateProjectDto): Promise<PopulatedProject> | Observable<PopulatedProject> | PopulatedProject;

  deleteProject(request: GetProjectDto): Promise<Project> | Observable<Project> | Project;

  stopProject(request: GetProjectDto): Promise<Project> | Observable<Project> | Project;

  startProject(request: GetDeploymentDto): Promise<Project> | Observable<Project> | Project;

  updateInstanceType(request: UpdateInstanceTypeDto): Promise<Project> | Observable<Project> | Project;

  rollbackProject(request: GetDeploymentDto): Promise<Deployment> | Observable<Deployment> | Deployment;

  redeployProject(request: CreateDeploymentDto): Promise<Deployment> | Observable<Deployment> | Deployment;

  retryAndDeployProject(request: GetDeploymentDto): Promise<Deployment> | Observable<Deployment> | Deployment;
}

export function ProjectsServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getAllProjects",
      "getProject",
      "createProject",
      "deleteProject",
      "stopProject",
      "startProject",
      "updateInstanceType",
      "rollbackProject",
      "redeployProject",
      "retryAndDeployProject",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ProjectsService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ProjectsService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PROJECTS_SERVICE_NAME = "ProjectsService";

export interface DeploymentServiceClient {
  createDeployment(request: CreateDeploymentDto): Observable<Deployment>;

  getDeployments(request: GetDeploymentsDto): Observable<Deployments>;

  getDeployment(request: GetDeploymentDto): Observable<Deployment>;

  stopDeployment(request: GetDeploymentDto): Observable<Deployment>;

  startDeployment(request: GetDeploymentDto): Observable<Deployment>;

  deleteDeployment(request: GetDeploymentDto): Observable<Deployment>;

  retryDeployment(request: GetDeploymentDto): Observable<Deployment>;

  getLogs(request: GetDeploymentDto): Observable<DeploymentLogs>;
}

export interface DeploymentServiceController {
  createDeployment(request: CreateDeploymentDto): Promise<Deployment> | Observable<Deployment> | Deployment;

  getDeployments(request: GetDeploymentsDto): Promise<Deployments> | Observable<Deployments> | Deployments;

  getDeployment(request: GetDeploymentDto): Promise<Deployment> | Observable<Deployment> | Deployment;

  stopDeployment(request: GetDeploymentDto): Promise<Deployment> | Observable<Deployment> | Deployment;

  startDeployment(request: GetDeploymentDto): Promise<Deployment> | Observable<Deployment> | Deployment;

  deleteDeployment(request: GetDeploymentDto): Promise<Deployment> | Observable<Deployment> | Deployment;

  retryDeployment(request: GetDeploymentDto): Promise<Deployment> | Observable<Deployment> | Deployment;

  getLogs(request: GetDeploymentDto): Promise<DeploymentLogs> | Observable<DeploymentLogs> | DeploymentLogs;
}

export function DeploymentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createDeployment",
      "getDeployments",
      "getDeployment",
      "stopDeployment",
      "startDeployment",
      "deleteDeployment",
      "retryDeployment",
      "getLogs",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("DeploymentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("DeploymentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const DEPLOYMENT_SERVICE_NAME = "DeploymentService";

export interface EnvServiceClient {
  getEnvs(request: GetDeploymentDto): Observable<Envs>;

  addEnvs(request: GetDeploymentDto): Observable<Envs>;

  removeEnvs(request: GetDeploymentsDto): Observable<Envs>;
}

export interface EnvServiceController {
  getEnvs(request: GetDeploymentDto): Promise<Envs> | Observable<Envs> | Envs;

  addEnvs(request: GetDeploymentDto): Promise<Envs> | Observable<Envs> | Envs;

  removeEnvs(request: GetDeploymentsDto): Promise<Envs> | Observable<Envs> | Envs;
}

export function EnvServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getEnvs", "addEnvs", "removeEnvs"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("EnvService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("EnvService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ENV_SERVICE_NAME = "EnvService";
