kind: ConfigMap 
apiVersion: v1 
metadata:
  name: {{ .Values.requestService.configMap }}
data:
  KAFKA_URL: {{ .Values.var.KAFKA_URL }}
  KAFKA_USERNAME: {{ .Values.var.KAFKA_USERNAME }}
  KAFKA_PASSWORD: {{ .Values.var.KAFKA_PASSWORD }}
  DB_URL: {{ .Values.requestService.dbName }}:27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.requestService.dbName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.requestService.dbName }}
  template:
    metadata:
      labels:
        app: {{ .Values.requestService.dbName }}
    spec:
      containers:
        - name: {{ .Values.requestService.dbName }}
          image: mongo:latest
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.requestService.dbName }}
spec:
  selector:
    app: {{ .Values.requestService.dbName }}
  type: ClusterIP
  ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.requestService.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.requestService.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.requestService.name }}
    spec:
      containers:
        - name: {{ .Values.requestService.name }}
          image: harisanker10/servel-request-service
          envFrom:
            - configMapRef:
                name: {{ .Values.requestService.configMap}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.requestService.name }}
spec:
  selector:
    app: {{ .Values.requestService.name }}
  type: ClusterIP
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000
---
