apiVersion: v2
name: helm
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

dependencies:
  - name: request-service
    repository: file://charts/request-service/
    version: "0.1.0"
  - name: registry
    repository: file://charts/registry
    version: "0.1.0"
  # - name: projects-service
  #   repository: file://charts/projects-service/
  #   version: "0.1.0"
  - name: build-service
    repository: file://charts/build-service/
    version: "0.1.0"
  - name: strimzi-kafka
    version: "0.1.0"
    repository: file://charts/strimzi-kafka/
  - name: strimzi-kafka-operator
    version: 0.38.0 # Use the desired version
    repository: https://strimzi.io/charts/
  - name: roles
    version: "0.1.0"
    repository: file://charts/roles/
